# VERSION   0.1

FROM ubuntu:14.04
MAINTAINER Mark Mims <mark@svds.com>

ENV TERM xterm

RUN \
apt-get update &&\
apt-get install -y curl openjdk-7-jre-headless axel uuid-runtime 

RUN \
curl -s http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key | apt-key add - &&\
echo 'deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh trusty-cdh5 contrib' > /etc/apt/sources.list.d/cloudera.list &&\
echo 'deb-src http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh trusty-cdh5 contrib' >> /etc/apt/sources.list.d/cloudera.list &&\
apt-get update &&\
apt-get install -y oozie-client oozie-server

# private and public mapping
EXPOSE 8020
EXPOSE 8888
EXPOSE 11000
EXPOSE 11443
EXPOSE 9090
EXPOSE 8088
EXPOSE 19888

# private only
#EXPOSE 80

# Define default command.
#CMD ["/usr/bin/cdh_startup_script.sh && bash"]
#CMD ["bash /usr/bin/cdh_startup_script.sh && bash"]
CMD ["cdh_startup_script.sh"]
